### ISSUE TITLE
Về việc nâng cấp phiên bản ứng dụng theo dõi tình hình dịch bệnh

### ISSUE THREAD

**Issue by MT0609** [Nguyen-Quoc-Thai/coronavirus-update#3]
Mình thấy project này khá tiềm năng, cũng được biết bạn có ý định phát triển một phiên bản mới hơn của phần mềm. Hi vọng bạn có thể công khai mã nguồn để mọi người cũng nhau học hỏi, chia sẻ kiến thức cũng như đóng góp một phần nào đấy giúp đẩy lùi tình hình dịch bệnh.
P/S: Bạn có thể liên hệ với tôi qua số điện thoại 0833877441 nếu cần thiết. Rất hi vọng được hợp tác với bạn trong dự án sắp tới.

**Comment by Nguyen-Quoc-Thai** [comment]
thích spam ko. bạn đập cho giờ
